#!/bin/bash

set -euo pipefail

clearup ()
{
    rm -f /tmp/input.json
}

trap clearup EXIT INT TERM

exec 3>&1
exec 1>&2
jq -M -S . < /dev/stdin > /tmp/input.json

if [ "$(jq -r '.source | has("fingerprint")' < /tmp/input.json)" = 'true' ]; then
    fingerprint=$(jq -r .source.fingerprint < /tmp/input.json)
else
    echo "You need to provide the fingerprint of GPG key."
    exit 1
fi

if [ "$(jq -r '.source | has("passphrase")' < /tmp/input.json)" = 'true' ]; then
    true
else
    echo "You need to provide the passphrase of GPG key."
    exit 1
fi

if [ "$(jq -r '.source | has("private_key")' < /tmp/input.json)" = 'true' ]; then
    true
else
    echo "You need to provide the GPG private key to sign Debian source packages."
    exit 1
fi

if [ "$(jq -r '.version | has("ppa")' < /tmp/input.json)" = 'true' ]; then
    ppa=$(jq -r .version.ppa < /tmp/input.json)
elif [ "$(jq -r '.source | has("ppa")' < /tmp/input.json)" = 'true' ]; then
    ppa=$(jq -r .source.ppa < /tmp/input.json)
else
    ppa=""
fi

json='{"version":{"ppa":"'"$ppa"'","fingerprint":"'"$fingerprint"'"}}'

jq -n "$json" >&3
